apiVersion: v1
kind: Namespace
metadata:
  name: spire
  labels:
    app: spire
    # istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: spire
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://spiffe.github.io/helm-charts-hardened
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spire-crds
  namespace: flux-system
spec:
  interval: 1m0s
  driftDetection:
    mode: enabled
  targetNamespace: spire
  releaseName: spire-crds
  chart:
    spec:
      chart: spire-crds
      sourceRef:
        kind: HelmRepository
        name: spire
        namespace: flux-system
      version: "*"
  install:
    createNamespace: true
