#
# Copyright (C) 2024 Telicent Limited
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -generic-file

resources:
  - ../../../../telicent/bases/pipeline-data/producer

components:
#   # Patches
  - ../../../../telicent/components/patches/labels/telicent/resource
#   - ../../../telicent/components/patches/job/securitycontext

patches:
  - path: patches/job/images.yaml
    target:
      kind: Job
      name: producer
    options:
      allowNameChange: true

# Generate config(s)
configMapGenerator:
  # Environment Variables
  - name: producer
    behavior: replace
    envs:
      - patches/producer.env

  # Configmap with data (assumed to be small!)
  - name: producer-generic-file-data
    behavior: create
    files:
      - data/config.py
      - data/file_1.ttl
      - data/file_2.ttl

# Labels are declared last to ensure tagging of all resources
labels:
  - pairs:
      app.kubernetes.io/name: producer-generic-file
      app: producer-generic-file
    includeTemplates: true
