apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../components/patches/labels/telicent/resource
configMapGenerator:
- envs:
  - producer.env
  name: producer
kind: Kustomization
labels:
- includeTemplates: true
  pairs:
    app: producer
    app.kubernetes.io/name: producer
resources:
- job.yaml
- serviceaccount.yaml
