apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kafka-ui
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://provectus.github.io/kafka-ui-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka-ui
  namespace: flux-system
spec:
  interval: 1m0s
  driftDetection:
    mode: enabled
  targetNamespace: kafka-ui
  releaseName: kafka-ui
  chart:
    spec:
      chart: kafka-ui
      sourceRef:
        kind: HelmRepository
        name: kafka-ui
        namespace: flux-system
      version: "*"
  install:
    createNamespace: true
  values:
    kafka:
      clusters:
        - name: yaml
          bootstrapServers: eventhub-dpn-sbx-uksouth-001.servicebus.windows.net:9093
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false
