apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - platform.yaml
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --ssh-hostkey-algos=rsa-sha2-512,rsa-sha2-256
    target:
      kind: Deployment
      name: (source-controller|image-automation-controller)
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        decryption:
          provider: sops
        postBuild:
          substitute:
            cert_manager_email:
            cluster_endpoint:
            cluster_env: 
            cluster_name: 
            data_producer1_domain: 
            domain:
            env: dpn
            federator_server_domain: 
            ia_domain: 
            kafka_brokers_iam:
            keycloak_domain: 
            vault_url: "https://ca.dsm.neso.energy"
    target:
      kind: Kustomization
