apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - platform.yaml
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --ssh-hostkey-algos=rsa-sha2-512,rsa-sha2-256
    target:
      kind: Deployment
      name: (source-controller|image-automation-controller)
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        decryption:
          provider: sops
        postBuild:
          substitute:
            cert_manager_email: CHANGE_TO_CERT_MANAGER_EMAIL
            cluster_endpoint:
            cluster_env: CHANGE_TO_CLUSTER_NAME
            cluster_name: CHANGE_TO_CLUSTER_NAME
            data_producer1_domain: "CHANGE_TO_DATA_PRODUCER_DOMAIN"
            domain: "CHANGE_TO_DOMAIN"
            env: dpn
            federator_server_domain: "CHANGE_TO_MY_FEDERATOR_SERVER_DOMAIN"
            kafka_brokers_iam:
            region: eu-west-2
            vault_url: "https://ca.dsm.neso.energy"
    target:
      kind: Kustomization
