apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - platform.yaml
patches:
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        decryption:
          provider: sops
        postBuild:
          substitute:
            authorisation_api_domain:
            cert_manager_email:
            cluster_endpoint:
            cluster_env: 
            cluster_name: 
            data_producer1_domain: 
            data_producer2_domain: 
            data_producer3_domain: 
            domain: 
            federator_server_domain: 
            ia_domain:
            keycloak_domain: 
            oauth2_proxy_client_secret: 
            oauth2_proxy_cookie_secret:
            vault_url: "https://ca.dsm.neso.energy"
    target:
      kind: Kustomization