apiVersion: v1
kind: Namespace
metadata:
  name: dsi-data-pipelines
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: [DATA_PRODUCT]-ingestion-adaptor
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://YOUR_ACR_NAME.azurecr.io
  type: oci
  provider: azure
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: [DATA_PRODUCT]-ingestion-adaptor
  namespace: flux-system
spec:
  interval: 1m0s
  driftDetection:
    mode: enabled
  targetNamespace: dsi-data-pipelines
  releaseName: [DATA_PRODUCT]-ingestion-adaptor
  install:
    createNamespace: true
  upgrade:
    force: true
  chart:
    spec:
      chart: helm/adaptor-[DATA_PRODUCT]
      sourceRef:
        kind: HelmRepository
        name: [DATA_PRODUCT]-ingestion-adaptor
        namespace: flux-system
      version: "*"
  values:
    image_semver: YOUR_IMAGE_SEMVER
    image_name: YOUR_ACR_NAME.azurecr.io/[IMAGE_NAME]
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: [DATA_PRODUCT]-mapper-schema-assurance
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://YOUR_ACR_NAME.azurecr.io
  type: oci
  provider: azure
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: [DATA_PRODUCT]-mapper-schema-assurance
  namespace: flux-system
spec:
  interval: 1m0s
  driftDetection:
    mode: enabled
  targetNamespace: dsi-data-pipelines
  releaseName: [DATA_PRODUCT]-mapper-schema-assurance
  install:
    createNamespace: true
  upgrade:
    force: true
  chart:
    spec:
      chart: helm/mapper-schema-assurance-[DATA_PRODUCT]
      sourceRef:
        kind: HelmRepository
        name: [DATA_PRODUCT]-mapper-schema-assurance
        namespace: flux-system
      version: "*"
  values:
    image_semver: YOUR_IMAGE_SEMVER
    image_name: YOUR_ACR_NAME.azurecr.io/[IMAGE_NAME]
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: [DATA_PRODUCT]-mapper-security-labels
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://YOUR_ACR_NAME.azurecr.io
  type: oci
  provider: azure
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: [DATA_PRODUCT]-mapper-security-labels
  namespace: flux-system
spec:
  interval: 1m0s
  driftDetection:
    mode: enabled
  targetNamespace: dsi-data-pipelines
  releaseName: [DATA_PRODUCT]-mapper-security-labels
  install:
    createNamespace: true
  upgrade:
    force: true
  chart:
    spec:
      chart: helm/mapper-security-labels
      sourceRef:
        kind: HelmRepository
        name: [DATA_PRODUCT]-mapper-security-labels
        namespace: flux-system
      version: "*"
  values:
    image_semver: YOUR_IMAGE_SEMVER
    image_name: YOUR_ACR_NAME.azurecr.io/[IMAGE_NAME]
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: [DATA_PRODUCT]-mapper-extractor
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://YOUR_ACR_NAME.azurecr.io
  type: oci
  provider: azure
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: [DATA_PRODUCT]-mapper-extractor
  namespace: flux-system
spec:
  interval: 1m0s
  driftDetection:
    mode: enabled
  targetNamespace: dsi-data-pipelines
  releaseName: [DATA_PRODUCT]-mapper-extractor
  install:
    createNamespace: true
  upgrade:
    force: true
  chart:
    spec:
      chart: helm/mapper-extractor-[DATA_PRODUCT]
      sourceRef:
        kind: HelmRepository
        name: [DATA_PRODUCT]-mapper-extractor
        namespace: flux-system
      version: "*"
  values:
    image_semver: YOUR_IMAGE_SEMVER
    image_name: YOUR_ACR_NAME.azurecr.io/[IMAGE_NAME]
