apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        decryption:
          provider: sops
        postBuild:
          substitute:
            cert_manager_email: CHANGE_TO_CERT_MANAGER_EMAIL
            cluster_endpoint:
            cluster_env: CHANGE_TO_CLUSTER_NAME
            cluster_name: CHANGE_TO_CLUSTER_NAME
            domain: "CHANGE_TO_DOMAIN"
            env: dpn
            kafka_brokers_iam:
            karpenter_version: "1.0.6"
            region: eu-west-2
    target:
      kind: Kustomization
