apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        decryption:
          provider: sops
        postBuild:
          substitute:
            luster_env: 
            cluster_name: 
            domain:
            env: 
    target:
      kind: Kustomization
  - patch: |
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: controller
          annotations:
            azure.workload.identity/client-id: 
            azure.workload.identity/tenant-id:
    target:
        kind: ServiceAccount
        name: "(source-controller|image-reflector-controller)"
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: controller
        labels:
          azure.workload.identity/use: "true"
      spec:
        template:
          metadata:
            labels:
              azure.workload.identity/use: "true"
    target:
      kind: Deployment
      name: "(source-controller|image-reflector-controller)"