apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    app: vault
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 1m0s
  driftDetection:
    mode: enabled
  targetNamespace: vault
  releaseName: vault
  install:
    createNamespace: true
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: "*"
  values:
    server:
      dev:
        enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: flux-system
spec:
  interval: 1m0s
  driftDetection:
    mode: enabled
  targetNamespace: vault-secrets-operator-system
  releaseName: vault-secrets-operator
  install:
    createNamespace: true
  chart:
    spec:
      chart: vault-secrets-operator
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: "*"
