#
# Copyright (C) 2024 Telicent Limited
#
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: federation-server-ingress

spec:
  hosts:
    - "hosts.override.required"
  gateways:
    - istio-system/ingress-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: federator-server
            port:
              number: 8080
