apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    app: redis

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://registry-1.docker.io/bitnamicharts/redis
  ref:
    semver: "20.7.1"

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  releaseName: redis
  targetNamespace: redis
  chartRef:
    kind: OCIRepository
    name: redis
    namespace: flux-system
  install:
    createNamespace: true
  interval: 1h
  values:
    usePassword: false
    auth:
      enabled: false
    master:
      service:
        type: ClusterIP
        port: 6379
    cluster:
      enabled: true
    sentinel:
      enabled: false
