#
# Copyright (C) 2024 Telicent Limited
#
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: query-ui-ingress

spec:
  hosts:
    - "hosts.override.required"
  gateways:
    - istio-system/ingress-gateway
  http:
    - match:
        - uri:
            exact: "/query"
      redirect:
        uri: /query/
    - match:
        - uri:
            prefix: /query/
      route:
        - destination:
            host: query-ui
            port:
              number: 80
