apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"
  - port:
      number: 443
      name: https-keycloak
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-ingressgateway-cert-keycloak
    hosts:
      - "CHANGE_TO_KEYCLOAK_HOSTNAME"
  - port:
      number: 443
      name: https-data-sharing
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-ingressgateway-cert-data-sharing
    hosts:
      - "CHANGE_TO_DATA_SHARING_HOSTNAME"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingressgateway-cert-data-sharing
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-cert-data-sharing
  commonName: "CHANGE_TO_DATA_SHARING_HOSTNAME"
  dnsNames:
      - "CHANGE_TO_DATA_SHARING_HOSTNAME"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
---
