apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    app: keycloak
    istio-injection: enabled
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: keycloak
  namespace: keycloak
spec:
  hosts:
  - "${keycloak_domain}"
  gateways:
  - istio-system/ingress-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: keycloak.keycloak.svc.cluster.local  # Fully qualified service name
        port:
          number: 80
---
#prod namespace cert-manager
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingressgateway-cert-keycloak
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-cert-keycloak
  commonName: "${keycloak_domain}"
  dnsNames:
      - "${keycloak_domain}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
