apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kiali
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://kiali.org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: istio-istiod
  driftDetection:
    mode: warn
  targetNamespace: istio-system
  releaseName: kiali-server
  install:
    createNamespace: true
  chart:
    spec:
      chart: kiali-server
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
      version: "*"
  values:
    auth:
      strategy: anonymous
