#
# Copyright (C) 2024 Telicent Limited
#
apiVersion: apps/v1
kind: Job

metadata:
  name: producer

spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 0.1.0
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: producer
          # image: telicent/generic-file-adapter:0.1.0
          image: CONTAINER_IMAGE/generic-file-adapter:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                # Note: this configmap needs to match the configmap name that includes the nameSuffix "-generic-file"
                name: producer-generic-file
          volumeMounts:
            - name: data-volume
              mountPath: /app/adapter/data

      volumes:
        - name: data-volume
          configMap:
            name: producer-generic-file-data
