#  Copyright (c) Telicent Ltd.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../components/patches/labels/telicent/resource
- ../../../components/patches/statefulset/annotations/prometheus
- ../../../components/patches/statefulset/securitycontext
configMapGenerator:
- envs:
  - server.env
  name: graph-server
- files:
  - config.ttl
  name: graph-server-fuseki
kind: Kustomization
labels:
- includeTemplates: true
  pairs:
    app: graph-server
    app.kubernetes.io/name: graph-server
resources:
- statefulset.yaml
- service.yaml
- serviceaccount.yaml
