apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spire
  namespace: flux-system
spec:
  dependsOn:
    - name: spire-crds
  interval: 1m0s
  driftDetection:
    mode: enabled
  targetNamespace: spire
  releaseName: spire
  chart:
    spec:
      chart: spire
      sourceRef:
        kind: HelmRepository
        name: spire
        namespace: flux-system
      version: "*"
  install:
    createNamespace: true
  values:
    global:
      openshift: false
      spire:
        clusterName: aks-dpn-sbx-uksouth-001
        # upstreamServerAddress: 85.210.136.192
        trustDomain: neso.energy
        caSubject:
          country: UK
          organization: dpn
          commonName: neso.energy
        recommendations:
          enabled: true
        namespaces:
          create: true
    tags:
      nestedChildFull: false
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: spire
  namespace: spire
spec:
  hosts:
  - "spire-dpn.${domain}"
  gateways:
  - istio-system/ingress-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: spire-server.spire.svc.cluster.local  # Fully qualified service name
        port:
          number: 443
