#
# Copyright (C) 2024 Telicent Limited
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-ui
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: query-ui
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: query-ui
        app.kubernetes.io/version: "1.0.2"
    spec:
      serviceAccountName: query-ui
      containers:
        - name: query-ui
          image: telicent/telicent-query:1.0.2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: app-config-volume
              mountPath: /usr/share/nginx/html/query/env-config.js
              subPath: env-config.js
          resources:
            requests:
              memory: 512Mi
              cpu: 125m
            limits:
              memory: 512Mi
              cpu: 125m
          readinessProbe:
            httpGet:
              path: /query/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /query/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 2
      volumes:
        - name: app-config-volume
          configMap:
            name: query-ui-env-configjs
