#
# Copyright (C) 2024 Telicent Limited
#
apiVersion: v1
kind: Service
metadata:
  name: query-ui
spec:
  selector:
    app.kubernetes.io/name: query-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
