apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: datahub
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://helm.datahubproject.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: datahub-prerequisites
  namespace: flux-system
spec:
  interval: 1m0s
  driftDetection:
    mode: enabled
  targetNamespace: datahub
  releaseName: prerequisites
  install:
    createNamespace: true
  upgrade:
    force: true
  chart:
    spec:
      chart: datahub-prerequisites
      sourceRef:
        kind: HelmRepository
        name: datahub
        namespace: flux-system
      version: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: datahub
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: datahub-prerequisites
  interval: 1m0s
  driftDetection:
    mode: enabled
  targetNamespace: datahub
  releaseName: datahub
  install:
    createNamespace: true
  upgrade:
    force: true
  chart:
    spec:
      chart: datahub
      sourceRef:
        kind: HelmRepository
        name: datahub
        namespace: flux-system
      version: "*"
  values:
    datahub-frontend:
      image:
        registry: "acrdsmsbxuksouth001.azurecr.io"
        repository: datahub-frontend-react
        tag: v20241118.7
