apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../components/patches/labels/telicent/resource
configMapGenerator:
- envs:
  - mapper.env
  name: mapper
kind: Kustomization
labels:
- includeTemplates: true
  pairs:
    app: mapper
    app.kubernetes.io/name: mapper
resources:
- deployment.yaml
- serviceaccount.yaml
- service.yaml
