apiVersion: v1
kind: ConfigMap
metadata:
  name: authorisation-api
  namespace: tc-system
  labels:
    app: authorisation-api
data:
  MONGO_PROTOCOL: 'mongodb'
  MONGO_USER: ''
  MONGO_HOST: ''
  MONGO_PORT: '10255'
  MONGO_QUERY_STRING: '?ssl=true&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@YOUR_COSMOS_DB_NAME@'
