apiVersion: v1
kind: Service

metadata:
  name: authorisation-api
  namespace: tc-federation
  labels:
    app: authorisation-api-service
spec:
  selector:
    k8s-app: authorisation-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: authorisation
  namespace: tc-federation

spec:
  hosts:
    - "${authorisation_api_domain}"
  gateways:
    - istio-system/ingress-gateway
  http:
    - match:
        - uri:
            prefix: /authorisation-api
      rewrite:
        uriRegexRewrite:
          match: ^/authorisation-api(/|$)(.*)
          rewrite: /\2
      route:
        - destination:
            host: authorisation-api.tc-federation.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: terminate-mtls-authorisation-api
  namespace: tc-federation
spec:
  workloadSelector:
    matchLabels:
      app: authorisation-api-service
  host: ${authorisation_api_domain}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy

metadata:
  name: allow-ingress-authorisation-api
  namespace: tc-federation

spec:
  selector:
    matchLabels:
      k8s-app: authorisation-api
  action: ALLOW
  rules:
    - from:
        - source:
            principals: ["*"]
      to:
        - operation:
            methods: ["*"]
