# Copyright (C) 2024 Telicent Limited
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbac-federation-filter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pbac-federation-filter
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pbac-federation-filter
        app.kubernetes.io/version: "0.8.0"
    spec:
      serviceAccountName: pbac-federation-filter
      containers:
        - name: pbac-federation-filter
          image: telicent/telicent-pbac-federation-filter:0.8.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: pbac-federation-filter-config
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 250m
          volumeMounts: []
      volumes: []
      # readinessProbe:
      #   httpGet:
      #     path: /access/health
      #     port: 8080
      #     scheme: HTTP
      #   initialDelaySeconds: 60
      #   periodSeconds: 30
      #   timeoutSeconds: 2
      # livenessProbe:
      #   httpGet:
      #     path: /access/health
      #     port: 8080
      #     scheme: HTTP
      #   initialDelaySeconds: 60
      #   periodSeconds: 30
      #   timeoutSeconds: 2
